# Bernouli Random Variable

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp

In [7]:
prob = 0.3

r = tfp.distributions.Bernoulli(probs=prob, dtype=tf.float32).sample(sample_shape=(10,1))
r

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [4]:
y_prev = tf.random.normal((10,1))
y_prev

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.12566224],
       [ 0.34308538],
       [-0.2083352 ],
       [ 1.0918518 ],
       [ 0.5869125 ],
       [ 1.6654887 ],
       [ 0.744006  ],
       [ 0.15397406],
       [ 0.61906725],
       [ 1.7744037 ]], dtype=float32)>

In [5]:
tf.math.multiply(y_prev, r)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.12566224],
       [ 0.34308538],
       [-0.        ],
       [ 0.        ],
       [ 0.5869125 ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ],
       [ 0.        ]], dtype=float32)>

# Dropout layer

In [ ]:
from tensorflow import keras

In [ ]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28, 28]),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(300, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(10, activation="softmax")
])
model.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])
# n_epochs = 2
# history = model.fit(X_train_scaled, y_train, epochs=n_epochs,
#                     validation_data=(X_valid_scaled, y_valid))

In [ ]:
model.summary()


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_3 (Flatten)          (None, 784)               0         
_________________________________________________________________
dropout (Dropout)            (None, 784)               0         
_________________________________________________________________
dense_10 (Dense)             (None, 300)               235500    
_________________________________________________________________
dropout_1 (Dropout)          (None, 300)               0         
_________________________________________________________________
dense_11 (Dense)             (None, 100)               30100     
_________________________________________________________________
dropout_2 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_12 (Dense)             (None, 10)               

In [12]:
layer = tf.keras.layers.Dropout(.3, input_shape=(1,))

In [13]:
layer

In [14]:
data = tf.random.normal((10,1))
data

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-1.0084137 ],
       [-2.0226781 ],
       [ 1.6712183 ],
       [-2.3935676 ],
       [ 2.1989815 ],
       [ 0.93201345],
       [ 1.1521932 ],
       [ 0.55784875],
       [ 1.1622975 ],
       [-2.9098933 ]], dtype=float32)>

In [15]:
layer(data, training=True)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-1.440591 ],
       [-2.8895402],
       [ 2.3874547],
       [-3.4193823],
       [ 3.1414022],
       [ 0.       ],
       [ 0.       ],
       [ 0.7969268],
       [ 0.       ],
       [-4.1569905]], dtype=float32)>

In [16]:
l = tf.keras.layers.Dropout(.1, input_shape=(1,))

In [17]:
d = tf.ones((10,1))*5
d

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.]], dtype=float32)>

In [18]:
l(d, training=True)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[5.555556],
       [0.      ],
       [5.555556],
       [5.555556],
       [0.      ],
       [5.555556],
       [5.555556],
       [5.555556],
       [5.555556],
       [5.555556]], dtype=float32)>

In [20]:
5*(1/(1-0.1))

5.555555555555555